### ISSUE TITLE
Tracking Service MVP 개발

### ISSUE THREAD

**Issue by kimgunwooo** [team-chang-ppo/location_tracking_module_backend#9]
## 🤷 구현할 기능
트래킹 관련 MVP 기능 개발

## 🔨 상세 작업 내용
- [ ] 트래킹 연결 API
- [ ] 실제 트래킹 (DB 저장) API
- [ ] 종료 처리 API
- [ ] 트래킹 정보 받아오기 API

## 📄 참고 사항
트래킹 연결을 시작하면 token 반환
추후 확장을 위한 권한 정보를 추가하지만, 현재 사용은 안할예정

## ⏰ 예상 소요 기간
1일
